version: '3'

services:
  signaler:
    build: .
    #image: jwilder/docker-gen
    environment:
      GENERATOR: self-signed
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data:/data
